### ISSUE TITLE
/raster/clip returning empty image

### ISSUE THREAD

**Issue by johnkit** [OpenGeoscience/resonantgeodata#7]
I think I have the docker-compose built/running correctly, but when I try to clip an image, an empty image is returned.

* I am using the TerraColor image of San Francisco, downloaded from http://www.terracolor.net/download/tc_ng_sfbay_us_geotiff.zip  (~50MB)
* My clipping geometry (which covers most of the image) is {"coordinates": [[[-122.81, 37.5], [-122.81, 38.0], [-121.81, 38.0], [-121.81, 37.5], [-122.81, 37.5]]], "type": "Polygon"}
* For reference, the image corner points (via gdal 2.2) are [[-122.71879201711467, 38.052231141926995], [-122.71879201711467, 37.45219874192699], [-122.11875961711466, 38.052231141926995], [-122.11875961711466, 37.45219874192699]]
* For what it's worth, my full URL is http://localhost:8989/api/v1/raster/clip?itemId=5b5777d5aad49c000695a60a&geometry=%7B%22coordinates%22%3A%20%5B%5B%5B-122.81%2C%2037.5%5D%2C%20%5B-122.81%2C%2038.0%5D%2C%20%5B-121.81%2C%2038.0%5D%2C%20%5B-121.81%2C%2037.5%5D%2C%20%5B-122.81%2C%2037.5%5D%5D%5D%2C%20%22type%22%3A%20%22Polygon%22%7D&name=clipped&folderId=5b5777d4aad49c000695a602

@dorukozturk can you try this when you have time?

**Comment by dorukozturk** [comment]
@johnkit Will do thanks for trying.
